// <auto-generated />
using System;
using Api.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.EF.Migrations
{
    [DbContext(typeof(LunchAppDbContext))]
    partial class LunchAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Entities.LunchRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("LunchRecords");
                });

            modelBuilder.Entity("Api.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("LunchRecordPerson", b =>
                {
                    b.Property<int>("ConsumedLunchRecordsId")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumersId")
                        .HasColumnType("integer");

                    b.HasKey("ConsumedLunchRecordsId", "ConsumersId");

                    b.HasIndex("ConsumersId");

                    b.ToTable("LunchRecordPerson");
                });

            modelBuilder.Entity("Api.Entities.LunchRecord", b =>
                {
                    b.HasOne("Api.Entities.Person", "Payer")
                        .WithMany("PaidLunchRecords")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("LunchRecordPerson", b =>
                {
                    b.HasOne("Api.Entities.LunchRecord", null)
                        .WithMany()
                        .HasForeignKey("ConsumedLunchRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("ConsumersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Entities.Person", b =>
                {
                    b.Navigation("PaidLunchRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
