name: React CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    working-directory: ./client

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20x
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: client/package-lock.json
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies  
        run: npm ci
      - name: Build  
        run: npm run build
      - name: Lint
        run: npm run lint --max-warnings=0
