name: React CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    working-directory: ./client

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages

    env:
      VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
      VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20x
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: client/package-lock.json
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies  
        run: npm ci
      - name: Build  
        run: npm run build
      - name: Lint
        run: npm run lint --max-warnings=0
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: client/dist

  deploy:

    runs-on: ubuntu-latest
    needs: build
    environment: github-pages

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: production-files
